include:
  - path: '../${UX_APP}.${DOMAIN}/docker-compose.yml'
  - path: '../${DEVELOPMENT_APP}.${DOMAIN}/docker/pre-producao/docker-
compose.yml'
  - path: '../${PRODUCTION_APP}.${DOMAIN}/docker-compose.yml'

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - DEVELOPMENT_APP=${DEVELOPMENT_APP}
      - PRODUCTION_APP=${PRODUCTION_APP}
      - TEST_APP=${TEST_APP}
      - UX_APP=${UX_APP}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
