services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=meu-dominio.aqui
    networks:
      - app_network

include:
  - path: '/var/www/ux-dona-fatima.duckdns.org/docker-compose.yml'

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
